services:
  drive_ros:
    container_name: drive_ros
    build:
      context: .
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 run drive_ros drive_ros_bridge
    expose:
      - 5000

  diff_drive_sim:
    container_name: diff_drive_sim
    build:
      context: .
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 run drive_ros diff_drive_sim
