services:
  drive_ros:
    build:
      context: .
      dockerfile: ros.Dockerfile
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 run drive_ros drive_ros_bridge

  test:
    build:
      context: .
      dockerfile: ros.Dockerfile
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 topic echo /cmd_drive
