services:
  drive_ros:
    container_name: drive_ros
    build:
      context: .
    # network_mode: host # This is to be used when running on real robots
    ports:
      - 5000:5000
    command: ros2 launch drive_ros sim_demo.launch.py
    volumes:
      - ./datasets/:/home/root/datasets/
