services:
  drive_ros:
    build:
      context: .
      dockerfile: ros.Dockerfile
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 run drive_ros drive_ros_bridge
    expose:
      - 5000

  diff_drive_sim:
    build:
      context: .
      dockerfile: ros.Dockerfile
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 run drive_ros diff_drive_sim
