[project]
name = "DRIVE_AGAIN"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "shapely",
    "numpy>=1.19.5",
    "black",
    "pytest",
    "numpy",
    "pynput",
    "matplotlib",
    "flask-socketio"
]

[tool.black]
line-length = 120
