[project]
name = "DRIVE_AGAIN"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "shapely",
    "numpy>=1.19.5",
    "black",
    "pytest",
    "numpy",
    "pynput",
    "matplotlib",
]

[tool.black]
line-length = 120
